site:
    resource: "@SiteBundle/Controller/DefaultController.php"
    prefix:   /
    type: annotation

director_rest:
    type: rest
    resource: IMDRest\DirectorBundle\Controller\RestController
    prefix: /rest

director:
    resource: "@DirectorBundle/Resources/config/routing.yml"
    prefix:   /directores

pelicula:
    resource: "@PeliculaBundle/Controller/PeliculaController.php"
    type: annotation
    prefix: /peliculas

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc