director_rest:
    type: rest
    resource: IMDRest\DirectorBundle\Controller\RestController
    prefix: /rest

director:
    resource: "@DirectorBundle/Resources/config/routing.yml"
    prefix:   /director

pelicula:
    resource: "@PeliculaBundle/Resources/config/routing.yml"
    prefix:   /pelicula

